In [7]:
import pandas as pd
df = pd.read_csv("Data/telco_churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# DATA INSPECTION:

In [8]:
df.shape                                               #checking dataset shape

(7043, 21)

In [9]:
df.columns                                             #checking column names

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [ ]:
df.tail()                                              #Last 5 rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [10]:
df.head()                                              #first 5 rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [12]:
df.info()                                              #Checking Data Types

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [13]:
df.isnull().sum()                                      #Checking Missing Values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [14]:
df.duplicated().sum()                                  #Checking duplicates rows

np.int64(0)

In [15]:
print ("Churn:" , 
df["Churn"].unique())
print ("Contract:" , 
df["Contract"].unique())
print ("PaymentMethod:" ,
df["PaymentMethod"].unique())                          #Checking unique/categorical values

Churn: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Contract: <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
PaymentMethod: <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

In [16]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [17]:
df["tenure"].min()                                     #checking numerical values for logical validation
df["tenure"].max()

np.int64(72)

In [18]:
df[df["tenure"]< 0]                                    #checking for negative values in tenure column

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [19]:
#Churn distribution
df["Churn"].value_counts()                             #checking number of churn customers both yes and no

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [20]:
#Churn distribution
df["Churn"].value_counts(normalize=True)*100           #checking percentage of churn customers

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [21]:
df["SeniorCitizen"].max()                              #checking senior citizen column for logical validation

np.int64(1)

# DATA CLEANING:

In [22]:
#Converting TotalCharges from string to numeric

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors = "coerce")

In [23]:
#Checking missing values created after conversion

df["TotalCharges"].isnull().sum()

np.int64(11)

In [24]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [25]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [26]:
#Checking unique values in gender

df["gender"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [27]:
#Checking Total charges data type conversion

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [29]:
#Checking the conversion of NaN TO 0 in TotalCharges column

df["TotalCharges"].isnull().sum()

np.int64(0)

# Exploratory Data Analysis (EDA)

## Phase 1: Pandas Statistical Analysis

### ​Q1: Are senior citizens more likely to cancel their subscription than younger customers?

In [31]:
# SeniorCitizen: 0=Not a senior citizen ,1=Senior citizen.
#Churn:No=Customer did not cancel, Yes=Customer cancelled.
# normalize=True gives us the % instead of raw counts, which is more accurate here
senior_churn = df.groupby('SeniorCitizen')['Churn'].value_counts(normalize=True).unstack() * 100

print("Churn Percentage - Senior Citizens:")
print(round(senior_churn, 2))

Churn Percentage - Senior Citizens:
Churn             No    Yes
SeniorCitizen
0              76.39  23.61
1              58.32  41.68

### Q2: Which internet service has the highest churn rate?

In [32]:
# checking churn rates across different internet service types
# using unstack to format the results into a clean grid
internet_churn = df.groupby('InternetService')['Churn'].value_counts(normalize=True).unstack() * 100

print("Internet Service Churn %:")
print(round(internet_churn, 2))

Internet Service Churn %:
Churn               No    Yes
InternetService
DSL              81.04  18.96
Fiber optic      58.11  41.89
No               92.60   7.40

### Q3: Do customers with streaming services stay longer with the company?

In [33]:
# separating customers who stream (TV or Movies) from those who don't
has_streaming = df[(df['StreamingTV'] == 'Yes') | (df['StreamingMovies'] == 'Yes')]
no_streaming = df[(df['StreamingTV'] == 'No') & (df['StreamingMovies'] == 'No')]

# comparing average tenure to check if streaming increases loyalty
print("Average tenure (streaming):", round(has_streaming['tenure'].mean(), 1), "months")
print("Average tenure (no streaming):", round(no_streaming['tenure'].mean(), 1), "months")

Average tenure (streaming): 39.1 months
Average tenure (no streaming): 22.1 months

### Q4: Are month-to-month customers more likely to churn than one-year and two-year contract?

In [34]:
# checking how contract length affects churn
# using crosstab to quickly get the row-wise percentages
contract_churn = pd.crosstab(df['Contract'], df['Churn'], normalize='index') * 100

print("Churn % by Contract Type:")
print(round(contract_churn, 2))

Churn % by Contract Type:
Churn              No    Yes
Contract
Month-to-month  57.29  42.71
One year        88.73  11.27
Two year        97.17   2.83

### Q5: At what tenure are customers most likely to cancel their service?

In [35]:
# isolating customers who actually left
# checking the basic stats (mean, median, etc.) to spot when most drop-offs happen
churned_customers = df[df['Churn'] == 'Yes']

print("Tenure stats for churned customers:")
print(churned_customers['tenure'].describe())

Tenure stats for churned customers:
count    1869.000000
mean       17.979133
std        19.531123
min         1.000000
25%         2.000000
50%        10.000000
75%        29.000000
max        72.000000
Name: tenure, dtype: float64

### Q6: Does having higher monthly charges increase the likelihood of churn?

In [36]:
# comparing average monthly bills: churned vs retained
charge_impact = df.groupby('Churn')['MonthlyCharges'].mean()

print("Avg monthly charges:")
print(round(charge_impact, 2))

Avg monthly charges:
Churn
No     61.27
Yes    74.44
Name: MonthlyCharges, dtype: float64

### Q7: Which payment method has the highest churn rate?

In [37]:
# checking if payment type (like auto-pay vs electronic checks) impacts churn
payment_churn = df.groupby('PaymentMethod')['Churn'].value_counts(normalize=True).unstack() * 100

print("Churn % by payment method:")
print(round(payment_churn, 2))

Churn % by payment method:
Churn                         No    Yes
PaymentMethod
Bank transfer (automatic)  83.29  16.71
Credit card (automatic)    84.76  15.24
Electronic check           54.71  45.29
Mailed check               80.89  19.11

### Q8: Do customers using multiple services have lower churn than customers using fewer services?

In [38]:
# mapping churn to 1/0 so we can easily calculate the mean
df['Churn_Numeric'] = df['Churn'].map({'Yes': 1, 'No': 0})

# counting how many extra add-on services each customer has
extra_services = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport']
df['ExtraServiceCount'] = (df[extra_services] == 'Yes').sum(axis=1)

# checking if having more services lowers the churn rate
multi_service_churn = df.groupby('ExtraServiceCount')['Churn_Numeric'].mean() * 100

print("Churn % by number of add-on services:")
print(round(multi_service_churn, 2))

Churn % by number of add-on services:
ExtraServiceCount
0    29.75
1    38.85
2    23.76
3    12.43
4     5.32
Name: Churn_Numeric, dtype: float64

### Q9: How much total revenue is represented by customers who have churned?

In [39]:
# calculating the total financial hit from churned customers
# using pd.to_numeric defensively to catch any leftover blank spaces in the column
revenue_lost = pd.to_numeric(df[df['Churn'] == 'Yes']['TotalCharges'], errors='coerce').sum()

print("Total revenue lost from churn: $", round(revenue_lost, 2))

Total revenue lost from churn: $ 2862926.9

### Q10: Which customer group has high monthly charges but relatively low churn?

In [40]:
# finding which contract groups have high bills but stay loyal
# .agg() is super handy here to check both metrics at the same time
group_analysis = df.groupby('Contract').agg({
    'MonthlyCharges': 'mean',
    'Churn_Numeric': 'mean' 
})

# formatting the churn column so it reads as a clean % instead of a decimal
group_analysis['Churn_Numeric'] = group_analysis['Churn_Numeric'] * 100
group_analysis.rename(columns={'Churn_Numeric': 'Churn Rate (%)'}, inplace=True)

print("Avg Charge vs Churn by Contract:")
print(round(group_analysis, 2))

Avg Charge vs Churn by Contract:
                MonthlyCharges  Churn Rate (%)
Contract
Month-to-month           66.40           42.71
One year                 65.05           11.27
Two year                 60.77            2.83